site_name: 'Example Documentation'
repo_url: https://github.com/olivomarco/testolly4
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - Using azd to deploy: azd.md
  - Changelog: changelog.md

plugins:
  - techdocs-core
